name: 'awesome-release-name-action'
description: 'generate awesome release names'
branding:
  icon: 'tag'
  color: 'purple'

inputs:
  delimiter:
    description: 'word delimiter'
    required: false
    default: '-'
  length: 
    description: 'number of words'
    required: false
    default: '2'      
  useToken: 
    description: 'add a unique token to name'
    required: false
    default: 'false'
  capitalize:
    description: 'capitalise words'
    required: false
    default: 'false' 
  
outputs:
  release-name: # the output
    description: 'your new release name'
runs:
  using: 'node16'
  main: 'index.js'
